### ISSUE TITLE
单节点双副本的支持

### ISSUE THREAD

**Issue by zphj1987** [cocalele/PureFlash#44]
```bash
root@lab101:~# pfcli list_disk
+----------+--------------------------------------+--------+
| Store ID |                 uuid                 | Status |
+----------+--------------------------------------+--------+
|        1 | 87f5753a-d4b4-44dd-93cf-f67430d8ce67 |     OK |
|        1 | d992b5ee-ae23-4a1e-8d85-f0566c056390 |     OK |
+----------+--------------------------------------+--------+
```

```bash
root@lab101:~#  pfcli create_volume -v test_v1 -s 64G --rep 2
[main] ERROR com.netbric.s5.conductor.rpc.SimpleHttpRpc - Failed http GET http://127.0.0.1:49180/s5c/?op=create_volume&volume_name=test_v1&size=68719476736&rep_cnt=2
java.io.IOException: Failed RPC invoke, code:2, reason:only 1 stores available but replica is 2
	at com.netbric.s5.conductor.rpc.SimpleHttpRpc.invokeGET(SimpleHttpRpc.java:42)
	at com.netbric.s5.conductor.rpc.SimpleHttpRpc.invokeConductor(SimpleHttpRpc.java:75)
	at com.netbric.s5.cli.CliMain.cmd_create_volume(CliMain.java:201)
	at com.netbric.s5.cli.CliMain.access$000(CliMain.java:19)
	at com.netbric.s5.cli.CliMain$1.run(CliMain.java:92)
	at com.netbric.s5.cli.CliMain.main(CliMain.java:181)
[main] ERROR com.netbric.s5.cli.CliMain - Failed: Failed RPC invoke, code:2, reason:only 1 stores available but replica is 2
```
设置卷的副本数的时候，单个节点的时候好像是不允许多副本的，这个地方单节点多副本在某些场景上是有需求的,或者说没必要做这个限制或者能够通过参数来控制的

**Comment by qiyuanzhi** [comment]
单节点双副本当前设计上不支持，并非简单解除限制能够解决，需要在io路径上做一些开发
